<?php

namespace AppBundle\Repository;

/**
 * Support_MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Support_MailRepository extends \Doctrine\ORM\EntityRepository
{
}
